version: '3.8'

name: delivery-api

services:
  postgres:
    image: postgres:16
    container_name: delivery_postgres
    environment:
      POSTGRES_DB: delivery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: